# Example Site settings

#google_analytics: UA-NNNNNNNN-N
#

# Main website properties
title: "On-orbit ğŸ›°ï¸"
author: "Jorge M.G."

# Pages to be included in website's menu
header_pages:
  - index.md
  - pages/c_programming.md
  - pages/about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
